### ISSUE TITLE
La route /notes ne comprend pas celles dues aux absences

### ISSUE THREAD

**Issue by itsBayDev** [MauriaApp/API#2]
Je souhaite récupérer l'ensemble des notes d'un utilisateur pour calculer ses moyennes, celles dues aux absences sont donc très importantes dans mon cas d'utilisation 😅

Je ne sais pas si la création d'une route juste pour les notes suites aux absences est nécessaire mais ça m'arrangerait que tout soit regroupé dans l'existante `https://mauriaapi.fly.dev/notes`

![image](https://github.com/MauriaApp/API/assets/59513177/678f3e3b-9456-4d49-93e2-cbe43b467237)

**Comment by MylowMntr** [comment]
Je ne peux pas tout mettre dans une seule route, cela ferait dans tous les cas 2 appels en interne, car les 2 listes de notes ne sont pas accessibles depuis la même page... Il faut donc recharger 

(Il est possible de minimiser le code, mais je compte le faire très très prochainement, de ce fait, je mets cette solution en attendant)
